# program for counting number of nucleotides in DNA strand

# string of bases
nucleotides = 'GTCCATTTTGTAGATGGTTGTATTCAACTATCAAGAATAACTCGTAGTAGTGTACCAAGGAGAATCCGATTTTTCCGAGTAGAGGAAGTGCTCGGCAACATTACCGTACGAGTACATTGATTAATCTCGGATTTTTCACTGCTTGATTCAGCCTACCCAAGCCTGGGGTGGCGCTATGGCATGGTCCTGTGCCATCCGGTCTCCCTTTCCGTATTGGGAATCCTTAACTCACGTGATTGATCCTGGGGGCTGAGAACAGGAAAGGGATAGAGGACACGACTCGCCCGGCGGTACGGAATGGAATTAGTAGAGCGCCAAGTAGAATAGGACCAGCGTTCACAGATGTTGGCTATCAGTTCCGCCCGAAAGAAGAGGGTACAAACGGTATTACATCGTGCGGACGATGGGCCTCTGTAATTGCGTTGGGTAAGGCGTGCTCAATGAGGCTGGGTAGTCATGATACGAGCGTAACCAGGAAGTCCGGTGCGGCACAATGCATATCAGCTCCTTGGTACCTATCTAAGACGCAGGTTATTTACTATCGCACGAATCACGCATCAACGTACATCAATAGTGCAAATTCAAAACGGTCGAGGGGCCGTGTTCGGGGTGTACAATCTTTGGTCCAGGCAGGCAGTGATACCGCACTTTAGTAATACGAAAAAGATCTAACGACTCCTAGACCTCTATATGACATTAATTATGTCTTGGCGCCACTGTTCCGCCATGAGGAGCTAACTGACCATTGAGTTTAACTCCCTTAATGTGTGCTCCTGTTCAACAGCTCTTAATGCAACTAGGGGTACGGTGGAGCGAGTCGCAG'

# 'counter' variables for each base
a = 0
t = 0
c = 0
g = 0

# iterates through the string and adds 1 to the corresponding counter variable
for x in nucleotides:
    if x == 'G':
        g = g + 1
    elif x == 'A':
        a = a + 1
    elif x == 'T':
        t = t + 1
    else:
        c = c + 1

# prints the total number of each base
print (a, c, g, t)